from python import os;

os.system("clear");

print("Running all tests...");

# run all tests

if os.system("snake examples/hello.sk") != 0:
    print("Test failed: hello.sk");
    sys.exit(1);
if os.system("snake examples/logical_operators.sk") != 0:
    print("Test failed: logical_operators.sk");
    sys.exit(1);
if os.system("snake examples/enums.sk") != 0:
    print("Test failed: enums.sk");
    sys.exit(1);
if os.system("snake examples/list_type_check.sk") == 0:
    print("Test failed: list_type_check.sk");
    sys.exit(1);
if os.system("snake examples/math_example.sk") != 0:
    print("Test failed: math_example.sk");
    sys.exit(1);
if os.system("snake examples/structs.sk") != 0:
    print("Test failed: structs.sk");
    sys.exit(1);
if os.system("snake examples/imports.sk") != 0:
    print("Test failed: imports.sk");
    sys.exit(1);
if os.system("snake examples/dict_type_check.sk") == 0:
    print("Test failed: dict_type_check.sk");
    sys.exit(1);
if os.system("snake examples/type_check.sk") == 0:
    print("Test failed: type_check.sk");
    sys.exit(1);
if os.system("snake examples/argcv.sk test debug") != 0:
    print("Test failed: argcv.sk");
    sys.exit(1);
if os.system("snake examples/fibonacci.sk") != 0:
    print("Test failed: fibonacci.sk");
    sys.exit(1);
if os.system("snake examples/constants.sk") != 0:
    print("Test failed: constants.sk");
    sys.exit(1);
if os.system("snake examples/classes.sk") != 0:
    print("Test failed: classes.sk");
    sys.exit(1);
if os.system("snake examples/advanced_structs.sk") != 0:
    print("Test failed: advanced_structs.sk");
    sys.exit(1);
if os.system("snake examples/struct_errors.sk") == 0:
    print("Test failed: struct_errors.sk");
    sys.exit(1);
if os.system("snake examples/simple_struct.sk") != 0:
    print("Test failed: simple_struct.sk");
    sys.exit(1);
if os.system("snake examples/type_mod.sk") != 0:
    print("Test failed: type_mod.sk");
    sys.exit(1);
if os.system("snake examples/all_type_vars.sk") != 0:
    print("Test failed: all_type_vars.sk");
    sys.exit(1);
if os.system("snake examples/incdec.sk") != 0:
    print("Test failed: incdec.sk");
    sys.exit(1);
if os.system("snake examples/add_remove.sk") != 0:
    print("Test failed: add_remove.sk");
    sys.exit(1);
if os.system("snake examples/static_type_test.sk") == 0:
    print("Test failed: static_type_test.sk");
    sys.exit(1);
if os.system("snake examples/main_func.sk") != 0:
    print("Test failed: main_func.sk");
    sys.exit(1);
if os.system("snake examples/printall.sk") != 0:
    print("Test failed: printall.sk");
    sys.exit(1);
if os.system("snake examples/tiny_for.sk") != 0:
    print("Test failed: tiny_for.sk");
    sys.exit(1);
if os.system("snake examples/static_property.sk") != 0:
    print("Test failed: static_property.sk");
    sys.exit(1);
if os.system("snake examples/orelse.sk") != 0:
    print("Test failed: orelse.sk");
    sys.exit(1);
if os.system("snake examples/maybe.sk") != 0:
    print("Test failed: maybe.sk");
    sys.exit(1);

print("All tests passed!");
sys.exit(0);